sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.projectKey=Yaroslav731_php-project-48
sonar.organization=yaroslav731
sonar.sources=.
sonar.exclusions=/vendor/, /node_modules/, /tests/
sonar.sourceEncoding=UTF-8
